# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: MrMaksimize
description: Gov, Code, Thoughts. This is a place for me to speak freely and represent no one.
tagline: Gov Code Thoughts. This is a place for me to speak freely and represent no one.
url: localhost:4000
sidebar_img: http://mrm-random.s3.amazonaws.com/dz/maksim.jpg

lang: "en"
author: "Maksim Pecherskiy"
title: "{ Maksim Pecherskiy }"
description: "Maksim's Personal Site"
keywords: "maksim, pecherskiy"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# general setting for Jekyll
google-tracking-id: 'UA-31205267-1'

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink:   /:title/
paginate: 5
paginate_path: 'page:num'
excerpt_separator: '<!--break-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

#Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag


################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "http://mrm-screen.s3.amazonaws.com/me_clif.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "mrmaksimize"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "https://octodex.github.com/images/agendacat.png"
    date: "November 2014 - Today"
    description: "CDO @ City of San Diego"
  - image: "/img/timeline/baracktocat.jpg"
    date: "January 2014 - Nomber 2014"
    description: "Fellow @ Code For America"
  - image: "https://octodex.github.com/images/steroidtocat.png"
    date: "March 2013 - January 2014"
    description: "Senior Developer / Solutions Architect @ Promet Source"
  - image: "https://octodex.github.com/images/gangnamtocat.png"
    date: "May 2011 - February 2013"
    description: "Software Developer @ AllPlayers"
  - image: "https://octodex.github.com/images/luchadortocat.png"
    date: "September 2009 - May 2011"
    description: "Software Developer @ MrMaksimize"
  - image: "https://octodex.github.com/images/setuptocat.jpg"
    date: "August 2008"
    description: "First met Clifton (my cat)"
  - image: "https://octodex.github.com/images/foundingfather_v2.png"
    date: "September 1996"
    description: "Arrived to Chicago from Ukraine"
  - image: "https://octodex.github.com/images/total-eclipse-of-the-octocat.jpg"
    date: "September 1993"
    description: "First got my hands on a a computer"


# First image of the Timeline

timeline-img: "https://octodex.github.com/images/spidertocat.png"

###########
# Contact #
###########

email: "your@email.here"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
